DELETE FROM users_roles;
DELETE FROM estimates_history;
ALTER TABLE estimates_history AUTO_INCREMENT = 1;
DELETE FROM users;
ALTER TABLE users AUTO_INCREMENT = 1;
DELETE FROM roles;
ALTER TABLE roles AUTO_INCREMENT = 1;
INSERT INTO users (id, first_name, last_name, user_name, password, api_key, created) VALUES (DEFAULT, 'Tiresa', 'Dombrowski', 'tdombrowski', 'supersecret1', 'supersecret1', DEFAULT);
INSERT INTO users (id, first_name, last_name, user_name, password, api_key, created) VALUES (DEFAULT, 'Paul', 'Norby', 'pnorby', 'supersecret2', 'supersecret2', DEFAULT);
INSERT INTO users (id, first_name, last_name, user_name, password, api_key, created) VALUES (DEFAULT, 'Kyle', 'Maitland', 'kmaitland', 'supersecret3', 'supersecret3', DEFAULT);
INSERT INTO users (id, first_name, last_name, user_name, password, api_key, created) VALUES (DEFAULT, 'Yesid', 'Perea', 'yperea', 'supersecret4', 'supersecret4', DEFAULT);
INSERT INTO roles (id, role_name, created) VALUES (DEFAULT, 'administrator', DEFAULT);
INSERT INTO roles (id, role_name, created) VALUES (DEFAULT, 'user', DEFAULT);
INSERT INTO users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (3, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (4, 1);
INSERT INTO estimates_history (id, user_id, candy_per_children, children_population, address, country, latitude, longitude, created) VALUES (DEFAULT, 1, 5, 274, '2935 Broadbridge Ave, Stratford, CT', 'USA', NULL, NULL, DEFAULT);
INSERT INTO estimates_history (id, user_id, candy_per_children, children_population, address, country, latitude, longitude, created) VALUES (DEFAULT, 2, 10, 190, '1701 Wright Street, Madison, Wisconsin 53704', 'USA', NULL, NULL, DEFAULT);
INSERT INTO estimates_history (id, user_id, candy_per_children, children_population, address, country, latitude, longitude, created) VALUES (DEFAULT, 3, 15, 40, '223 W Main St, Madison, WI 53703', 'USA', NULL, NULL, DEFAULT);
INSERT INTO estimates_history (id, user_id, candy_per_children, children_population, address, country, latitude, longitude, created) VALUES (DEFAULT, 4, 5, 240, '201 S Gammon Rd, Madison, WI 53717', DEFAULT, NULL, NULL, DEFAULT);
